src/log_manager/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

#  Copyright (c) 2017 INFN - "Istituto Nazionale di Fisica Nucleare" - Italy
#  All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you may
#  not use this file except in compliance with the License. You may obtain
#  a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.

from django.urls import re_path as url
from openstack_dashboard.dashboards.idmanager.log_manager import views

urlpatterns = [
    url(r'^$', views.MainView.as_view(), name='index'),
    url(r'^(?P<log_id>[^/]+)/detail/$', views.DetailView.as_view(), name='detail')
]

src/project_manager/urls.py
#  Copyright (c) 2014 INFN - "Istituto Nazionale di Fisica Nucleare" - Italy
#  All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you may
#  not use this file except in compliance with the License. You may obtain
#  a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License. 


from django.urls import re_path as url
from openstack_dashboard.dashboards.idmanager.project_manager import views
from openstack_dashboard.dashboards.identity.projects import views as baseViews

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^create$', views.CreateProjectView.as_view(), name='create'),
    url(r'^subscribe$', views.SubscribeView.as_view(), name='subscribe'),
    url(r'^(?P<tenant_id>[^/]+)/update/$',
        views.UpdateProjectView.as_view(), name='update'),
    url(r'^(?P<tenant_id>[^/]+)/usage/$',
        views.ProjectUsageView.as_view(), name='usage'),
    url(r'^(?P<project_id>[^/]+)/detail/$',
        views.DetailProjectView.as_view(), name='detail'),
    url(r'^(?P<tenant_id>[^/]+)/update_quotas/$',
        baseViews.UpdateQuotasView.as_view(), name='update_quotas'),
    url(r'^(?P<project_id>[^/]+)/course/$',
        views.CourseView.as_view(), name='course'),
    url(r'^(?P<project_id>[^/]+)/course_detail/$',
        views.CourseDetailView.as_view(), name='course_detail'),
    url(r'^(?P<project_id>[^/]+)/edittags/$',
        views.EditTagsView.as_view(), name='edittags'),
    url(r'^proposedrenew/$',
        views.ProposedRenewView.as_view(), name='proposedrenew')
]

src/openstack_auth_shib/models.py
#  Copyright (c) 2014 INFN - "Istituto Nazionale di Fisica Nucleare" - Italy
#  All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you may
#  not use this file except in compliance with the License. You may obtain
#  a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License. 

from datetime import datetime
from datetime import timezone as tzone

from django.db import models
from django.utils import timezone

# Used bit mask for project status
PRJ_PRIVATE = 0
PRJ_PUBLIC = 1
PRJ_COURSE = 2

#
# Project request must be handled by cloud admin first
#
PSTATUS_REG = 0
#
# Project request must be handled by project admin
#
PSTATUS_PENDING = 1
#
# Project request must be checked for compliance
#
PSTATUS_CHK_COMP = 2
#
# Project request for admin election
#
PSTATUS_ADM_ELECT = 5
#
# Subscription renewal to be handled by cloud admin first
#
PSTATUS_RENEW_ADMIN = 10
#
# Subscription renewal to be handled by project admin
#
PSTATUS_RENEW_MEMB = 11
#
# Subscription renewal proposed to the user
#
PSTATUS_RENEW_ATTEMPT = 12
#
# Subscription renewal rejected to the user
#
PSTATUS_RENEW_DISC = 13

#
# Registration request is waiting for pre-check
#
RSTATUS_PENDING = 0
#
# Reminder for cloud admin (first step)
#
RSTATUS_REMINDER = 1
#
# Reminder for cloud admin (final step)
#
RSTATUS_REMINDACK = 2
#
# Orphan user scheduled for ban on gate
#
RSTATUS_DISABLING = 3
#
# Orphan user banned on gate
#
RSTATUS_DISABLED = 4
#
# Orphan user to be re-enabled on gate
#
RSTATUS_REENABLING = 5

OS_ID_LEN = 64
OS_LNAME_LEN = 255
OS_SNAME_LEN = 64
EXT_ACCT_LEN = OS_LNAME_LEN
EMAIL_LEN = 255
PWD_LEN = 64
DESCR_LEN = 500

# Persistent data
class Registration(models.Model):
    regid = models.AutoField(primary_key=True)
    #
    # user id as registered in keystone
    # it's null if and only if the user is not yet
    # registered in keystone
    #
    userid = models.CharField(
        max_length=OS_ID_LEN,
        db_index=True,
        null=True
    )
    #
    # user name as registered in keystone
    #
    username = models.CharField(
        max_length=OS_LNAME_LEN,
        unique=True
    )
    givenname = models.CharField(max_length=OS_LNAME_LEN)
    sn = models.CharField(max_length=OS_LNAME_LEN)
    organization = models.CharField(max_length=OS_LNAME_LEN)
    phone = models.CharField(max_length=OS_SNAME_LEN)
    domain = models.CharField(max_length=OS_SNAME_LEN)
    #
    # deprecated
    # but it can be used as max expiration date
    #
    expdate = models.DateTimeField(
        db_index=True,
        null=True
    )

class Project(models.Model):
    #
    # project name as registered in keystone
    #
    projectname = models.CharField(
        max_length=OS_SNAME_LEN,
        primary_key=True
    )
    #
    # project id as registered in keystone
    # it's null if and only if the project is not yet
    # registered in keystone
    #
    projectid = models.CharField(
        max_length=OS_ID_LEN,
        null=True
    )
    description = models.TextField()
    #
    # Type of project (private, public, course)
    #
    status = models.IntegerField()

class UserMapping(models.Model):
    #
    # the id provided by the SSO authority
    # for example the eduPersonPrincipalName
    #
    globaluser = models.CharField(
        max_length=EXT_ACCT_LEN,
        primary_key=True
    )
    registration = models.ForeignKey(Registration,
                                    db_index=False,
                                    on_delete=models.CASCADE)

class ExpManager(models.Manager):
    use_in_migrations = True

    def create_expiration(self, **kwargs):
        reg_item = kwargs['registration']
        result = self.model.objects.create(
            registration = reg_item,
            project = kwargs['project'],
            expdate = kwargs['expdate']
        )

        if reg_item.expdate < kwargs['expdate']:
            reg_item.expdate = kwargs['expdate']
            reg_item.save()

        return result

    def _operate_expiration(self, op, **kwargs):
        q_args = dict()
        if 'registration' in kwargs:
            q_args['registration'] = kwargs['registration']
        elif 'registration__regid' in kwargs:
            q_args['registration__regid'] = kwargs['registration__regid']
        elif 'registration__userid' in kwargs:
            q_args['registration__userid'] = kwargs['registration__userid']
        else:
            raise Exception('Missing registration')

        if 'project' in kwargs:
            q_args['project'] = kwargs['project']
        elif 'project__projectname' in kwargs:
            q_args['project__projectname'] = kwargs['project__projectname']
        elif 'project__projectid' in kwargs:
            q_args['project__projectid'] = kwargs['project__projectid']
        else:
            raise Exception('Missing project')

        prj_exp = self.model.objects.filter(**q_args)
        if len(prj_exp) == 0:
            return
        regid = prj_exp[0].registration.regid

        if op == 0:
            prj_exp.update(expdate = kwargs['expdate'])
        else:
            prj_exp.delete()

        all_exp = self.model.objects.filter(
            registration__regid = regid
        )
        if len(all_exp):
            new_exp = max([ x.expdate for x in all_exp ])
            all_exp[0].registration.expdate = new_exp
            all_exp[0].registration.save()
        else:
            newdate = datetime.now(tzone.utc)
            Registration.objects.filter(regid = regid).update(expdate = newdate)

    def update_expiration(self, **kwargs):
        self._operate_expiration(0, **kwargs)

    def delete_expiration(self, **kwargs):
        self._operate_expiration(1, **kwargs)


class Expiration(models.Model):
    objects = ExpManager()

    registration = models.ForeignKey(Registration, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    expdate = models.DateTimeField(db_index=True)

class EMail(models.Model):
    registration = models.ForeignKey(Registration, on_delete=models.CASCADE)
    email = models.EmailField(max_length=EMAIL_LEN)

class PrjRole(models.Model):
    registration = models.ForeignKey(Registration, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    roleid = models.CharField(max_length=OS_ID_LEN, null=False)
    status = models.IntegerField(default=0)

class PrjAttribute(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.IntegerField(default=0)
    value = models.TextField()

#Temporary data
class RegRequest(models.Model):
    registration = models.ForeignKey(Registration, on_delete=models.CASCADE)
    password = models.CharField(max_length=PWD_LEN, null=True)
    externalid = models.CharField(max_length=EXT_ACCT_LEN, null=True)
    email = models.EmailField(max_length=EMAIL_LEN)
    flowstatus = models.IntegerField(default=RSTATUS_PENDING)
    contactper = models.CharField(max_length=OS_LNAME_LEN, null=True)
    notes = models.TextField()

#Temporary data
class PrjRequest(models.Model):
    registration = models.ForeignKey(Registration, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    #
    # Process status of the request, see PSTATUS_* for possible values
    #
    flowstatus = models.IntegerField(default=PSTATUS_REG)
    notes = models.TextField()


class LogManager(models.Manager):
    use_in_migrations = True

    def log_action(self, log_type, action, message,
                   project_id=None, user_id=None,
                   project_name=None, user_name=None,
                   dst_project_id=None, dst_user_id=None,
                   extra={}):

        log = self.model.objects.create(
            log_type=log_type,
            action=action,
            message=message,
            project_id=project_id,
            user_id=user_id,
            project_name=project_name,
            user_name=user_name,
            dst_project_id=dst_project_id,
            dst_user_id=dst_user_id,
        )

        for k, v in extra.items():
            log.logextra_set.create(key=k, value=v)

        return log


class Log(models.Model):
    objects = LogManager()

    timestamp = models.DateTimeField(
        default=timezone.now,
        db_index=True,
        editable=False,
        blank=False,
    )

    log_type = models.CharField(
        max_length=255,
        db_index=True,
        blank=False,
    )

    action = models.CharField(
        max_length=255,
        db_index=True,
        blank=False,
    )

    project_id = models.CharField(
        max_length=OS_ID_LEN,
        db_index=True,
        null=True,
        blank=True,
    )

    user_id = models.CharField(
        max_length=OS_ID_LEN,
        db_index=True,
        null=True,
        blank=True,
    )

    project_name = models.CharField(
        max_length=OS_SNAME_LEN,
        db_index=True,
        null=True,
        blank=True,
    )

    user_name = models.CharField(
        max_length=OS_SNAME_LEN,
        db_index=True,
        null=True,
        blank=True,
    )

    dst_project_id = models.CharField(
        max_length=OS_ID_LEN,
        db_index=True,
        null=True,
        blank=True,
    )

    dst_user_id = models.CharField(
        max_length=OS_ID_LEN,
        db_index=True,
        null=True,
        blank=True,
    )

    message = models.TextField(
        blank=False,
    )


class LogExtra(models.Model):
    log = models.ForeignKey(Log, on_delete=models.PROTECT)

    key = models.CharField(
        max_length=255,
        db_index=True,

src/templates/project_manager/_course.html
{% extends "horizon/common/_modal_form.html" %}

{% comment %}
  Copyright (c) 2014 INFN - "Istituto Nazionale di Fisica Nucleare" - Italy
  All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License"); you may
  not use this file except in compliance with the License. You may obtain
  a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  License for the specific language governing permissions and limitations
  under the License. 
{% endcomment %}

{% load i18n %}

{% block form_id %}edit_course_form{% endblock %}
{% block form_action %}
{% url 'horizon:idmanager:project_manager:course' projectid %}
{% endblock %}

{% block modal-header %}{% trans "Edit Course" %}{% endblock %}

{% block modal-body %}
<div class="left">

    <fieldset>
    {% include "horizon/common/_form_fields.html" %}
    </fieldset>
    
</div>
<div class="right">
    <h3>{% trans "Description" %}:</h3>
    <p>{% trans "From here you can edit the course information." %}</p>    
</div>
{% endblock %}

{% block modal-footer %}
    
    <input type="button"
           class="btn btn-primary pull-right"
           onclick="location.href='{% url 'horizon:idmanager:project_manager:index' %}'"
           value="{% trans 'Cancel' %}"/>  
    <input id="okbtnid"
           class="btn btn-primary pull-right" 
           type="submit" 
           value="{% trans 'Ok' %}" />

{% endblock %}

src/templates/project_manager/_course_detail.html
{% extends "horizon/common/_modal_form.html" %}

{% comment %}
  Copyright (c) 2014 INFN - "Istituto Nazionale di Fisica Nucleare" - Italy
  All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License"); you may
  not use this file except in compliance with the License. You may obtain
  a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  License for the specific language governing permissions and limitations
  under the License. 
{% endcomment %}

{% load i18n %}

{% block form_id %}view_course_form{% endblock %}

{% block modal-header %}{% trans "Course References" %}{% endblock %}

{% block modal-body %}
    <fieldset>
    {% include "horizon/common/_form_fields.html" %}
    </fieldset>
{% endblock %}

{% block modal-footer %}
    
    <input type="button"
           class="btn btn-primary pull-right"
           onclick="copyAndJump()"
           value="{% trans 'Copy to clipboard' %}"/>  

{% endblock %}

{% block modal-js %}
<script id="scriptforclipboard" type="text/javascript">
function copyAndJump() {
  var copyText = document.getElementById("id_courseref");
  copyText.select();
  document.execCommand("copy");
  location.href="{% url 'horizon:idmanager:project_manager:index' %}";
}
</script>
{% endblock %}

src/templates/project_manager/_detail_overview.html
{% comment %}
  Copyright (c) 2014 INFN - "Istituto Nazionale di Fisica Nucleare" - Italy
  All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License"); you may
  not use this file except in compliance with the License. You may obtain
  a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  License for the specific language governing permissions and limitations
  under the License. 
{% endcomment %}

{% load i18n  %}

<h3>{% trans "Project Overview" %}</h3>

<div class="info detail">
  <h4>{% trans "Information" %}</h4>
  <hr class="header_rule">
  <dl class="dl-horizontal">
    <dt>{% trans "Project Name" %}</dt>
    <dd>{{ project.name }}</dd>
    <dt>{% trans "Project ID" %}</dt>
    <dd>{{ project.id }}</dd>
    <dt>{% trans "Enabled" %}</dt>
    <dd>{{ project.enabled }}</dd>
    <dt>{% trans "Description" %}</dt>
    <dd>{{ project.description|default:_("None") }}</dd>
    {% if prj_tags %}
    <dt>{% trans "Tags" %}</dt>
    <dd>{{ prj_tags }}</dd>
    {% endif %}
    {% if expiration %}
    <dt>{% trans "Expiration date" %}</dt>
    <dd>{{ expiration }}</dd>
    {% endif %}
    {% if cper %}
    <dt>{% trans "Contact person" %}</dt>
    <dd>{{ cper }}</dd>
    {% endif %}
    {% if organization %}
    <dt>{% trans "Home institution" %}</dt>
    <dd>{{ organization }}</dd>
    {% endif %}
    {% if org_unit %}
    <dt>{% trans "Unit or department" %}</dt>
    <dd>{{ org_unit }}</dd>
    {% endif %}
  </dl>

  {% if admin_list %}
  <hr class="header_rule">
  <h4>{% trans "Project administrators" %}</h4>
  <ul>
  {% for admin in admin_list %}
    <li>{{ admin.givenname }} {{ admin.sn }} ({{ admin.id }}): <a href="mailto:{{ admin.email }}">{{ admin.email }}</a></li>
  {% endfor %}
  </ul>
  {% endif %}
</div>

src/templates/project_manager/_edittags.html
{% extends "horizon/common/_modal_form.html" %}

{% comment %}
  Copyright (c) 2014 INFN - "Istituto Nazionale di Fisica Nucleare" - Italy
  All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License"); you may
  not use this file except in compliance with the License. You may obtain
  a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  License for the specific language governing permissions and limitations
  under the License. 
{% endcomment %}

{% load i18n %}

{% block form_id %}edit_tags_form{% endblock %}
{% block form_action %}
{% url 'horizon:idmanager:project_manager:edittags' projectid %}
{% endblock %}

{% block modal-header %}{% trans "Edit project tags" %}{% endblock %}

{% block modal-body %}
<div class="left">

    <fieldset>
    {% include "horizon/common/_form_fields.html" %}
    </fieldset>
    
</div>
<div class="right">
    <h3>{% trans "Description" %}:</h3>
    <p>{% trans "From here you can edit tags for" %} {{ projectname }}</p>    
</div>
{% endblock %}

{% block modal-footer %}
    
    <input type="button"
           class="btn btn-primary pull-right"
           onclick="location.href='{% url 'horizon:idmanager:project_manager:index' %}'"
           value="{% trans 'Cancel' %}"/>  
    <input id="okbtnid"
           class="btn btn-primary pull-right" 
           type="submit" 
           value="{% trans 'Ok' %}" />

{% endblock %}

src/templates/project_manager/_prj_request.html
{% extends "horizon/common/_modal_form.html" %}

{% comment %}
  Copyright (c) 2014 INFN - "Istituto Nazionale di Fisica Nucleare" - Italy
  All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License"); you may
  not use this file except in compliance with the License. You may obtain
  a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  License for the specific language governing permissions and limitations
  under the License. 
{% endcomment %}

{% load i18n %}

{% block form_id %}prj_request_form{% endblock %}
{% block form_action %}{% url 'horizon:idmanager:project_manager:subscribe' %}{% endblock %}

{% block modal_id %}prj_request_modal{% endblock %}
{% block modal-header %}{% trans "Submit request" %}{% endblock %}

{% block modal-body %}
<div class="left">
  <fieldset>
    {% include 'horizon/common/_form_errors.html' with form=form %}
    {% include 'horizon/common/_form_field.html' with field=form.prjaction %}
    <div id="selprjdiv" style="display: block;">
      {% include 'horizon/common/_form_field.html' with field=form.selprj %}
    </div>

     <div id="newprjdiv" style="display: none;">
    {% if form.fields.newprj %}
      {% include 'horizon/common/_form_field.html' with field=form.newprj %}
    {% endif %}
    {% if form.fields.prjdescr %}
      {% include 'horizon/common/_form_field.html' with field=form.prjdescr %}
    {% endif %}
    {% if form.fields.expiration %}
      {% include 'horizon/common/_form_field.html' with field=form.expiration %}
    {% endif %}
    {% if form.fields.contactper %}
      {% include 'horizon/common/_form_field.html' with field=form.contactper %}
    {% endif %}
    {% if form.fields.organization %}
      {% include 'horizon/common/_form_field.html' with field=form.organization %}
    {% endif %}
    {% if form.fields.org_unit %}
      {% include 'horizon/common/_form_field.html' with field=form.org_unit %}
    {% endif %}
    </div>

    {% include 'horizon/common/_form_field.html' with field=form.notes %}
  </fieldset>
</div>
<div class="right">
    <h3>{% trans "Description:" %}</h3>
    <p>{% trans "From here you can submit a request for a project." %}</p>
    <div id="prjcompldiv" class="alert alert-info" style="display: none;">
        <p>{% trans "The selected project requires INFN rules compliance" %}</p>
        <p>
            {% trans "For further details see the " %}
            <a href="https://userguide.cloudveneto.it/en/latest/Registration.html#prerequisites-for-using-infn-resources">
                {% trans "user guide" %}
            </a>
        </p>
    </div>
</div>
{% endblock %}

{% block modal-footer %}
    <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
    <button type="button"
              onclick="location.href='{% url 'horizon:project:overview:index' %}'"
              class="btn btn-primary pull-right">{% trans "Cancel" %}</button>
{% endblock %}

{% block modal-js %}
  <script type="text/javascript">
    {# https://stackoverflow.com/questions/66663533/changing-values-of-a-combobox-in-javascript #}
    var orgData = [
      { org: '-', ouList: [ '-' ] },
    {% for orgName, orgUnits in org_table.items %}
      { org: '{{ orgName }}', ouList: [ {% for ouItem in orgUnits %}'{{ ouItem }}',{% endfor %}] },
    {% endfor %}
    ]
    const getOrgUnits = function(selectedOrg) {
      const target = orgData.find(d => d.org === selectedOrg);
      return target ? target.ouList : [];
    }
    const changeOrgUnits = function(orgUnits) {
      let html = ''
      for (let i in orgUnits) {
        html += '<option value="' + orgUnits[i] + '">' + orgUnits[i] + '</option>'
        document.querySelector('#id_org_unit').innerHTML = html;
      }
    }
    document.querySelector('#id_organization').addEventListener('change', (event) => {
      const orgUnits = getOrgUnits(event.target.value);
      changeOrgUnits(orgUnits);
    });

    document.querySelector('#id_prjaction').addEventListener('change', (event) => {
      if (event.target.value === 'selprj') {
        document.getElementById('selprjdiv').style.display='block';
        document.getElementById('newprjdiv').style.display='none';
      } else {
        document.getElementById('selprjdiv').style.display='none';
        document.getElementById('newprjdiv').style.display='block';
      }
    });

    document.querySelector('#id_selprj').addEventListener('change', (event) => {
        if (event.target.value.slice(0, 2) === 'c:') {
            document.getElementById('prjcompldiv').style.display='block';
        } else {
            document.getElementById('prjcompldiv').style.display='none';
        }
    });

  </script>
{% endblock %}

src/templates/project_manager/_proposedrenew.html
{% extends "horizon/common/_modal_form.html" %}

{% comment %}
  Copyright (c) 2014 INFN - "Istituto Nazionale di Fisica Nucleare" - Italy
  All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License"); you may
  not use this file except in compliance with the License. You may obtain
  a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  License for the specific language governing permissions and limitations
  under the License. 
{% endcomment %}

{% load i18n %}

{% block form_id %}proposed_renewal_form{% endblock %}
{% block form_action %}
{% url 'horizon:idmanager:project_manager:proposedrenew' %}
{% endblock %}

{% block modal-header %}{% trans "Your affiliation is going to expire" %}{% endblock %}

{% block modal-body %}
    <p>{% trans "Do you want to renew your affilition to" %} {{ project }}?</p>
    <fieldset>
    {% include "horizon/common/_form_fields.html" %}
    </fieldset>
{% endblock %}

{% block modal-footer %}
    
    <input type="button"
           class="btn btn-primary pull-right"
           onclick="RenewAction()"
           value="{% trans 'Yes' %}"/>  

    <input type="submit"
           class="btn btn-primary pull-right"
           value="{% trans 'No' %}"/>  

{% endblock %}

{% block modal-js %}
<script id="scriptforclipboard" type="text/javascript">
function RenewAction() {
  document.getElementById('id_action').value="renew";
  document.forms['proposed_renewal_form'].submit();
}
</script>
{% endblock %}

src/templates/project_manager/course.html
{% extends 'base.html' %}

{% comment %}
  Copyright (c) 2014 INFN - "Istituto Nazionale di Fisica Nucleare" - Italy
  All Rights Reserved.

  Licensed under the Apache License, Version 2.0 (the "License"); you may
  not use this file except in compliance with the License. You may obtain
  a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  License for the specific language governing permissions and limitations
  under the License. 
{% endcomment %}

{% load i18n %}
{% block title %}{% trans "Course information" %}{% endblock %}

{% block page_header %}
  {# to make searchable false, just remove it from the include statement #}
  {% include "horizon/common/_page_header.html" with title="Course information" %}
{% endblock page_header %}

{% block main %}
    {% include 'idmanager/project_manager/_course.html' %}
{% endblock %}